identifier: l77545g3k5a45brc
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: D:\ANGULAR-PROJECTS\my-blog
distFolder: dist/my-blog
outDir: D:\ANGULAR-PROJECTS\my-blog\dist\static
handle404: ''
allowErrorCollect: true
